### ISSUE TITLE
error[E0635]: unknown feature `proc_macro_span_shrink`

### ISSUE THREAD

**Issue by tony-ist** [aptlyundecided/super-blank-rust-pico-project#1]
This error shows when running `cargo run --bin blinky`.
Seems like `proc_macro2` is out of date in `Cargo.lock`.

This is solved with 
```
➜  super-blank-rust-pico-project git:(master) cargo update proc-macro2
    Updating crates.io index
    Updating proc-macro2 v1.0.49 -> v1.0.89
```

Would be a good idea to update the version in the repo also, so that future embedded noobies like myself have no problem setting this up.

**Comment by aptlyundecided** [comment]
Thanks for this!  I'm not really maintaining this project anymore so my awareness of it's viability is unfortunately low.

**Comment by aptlyundecided** [comment]
Updated cargo.lock, was able to successfully build.  Thank you again!
